version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    container_name: game-admin
    restart: always
    environment:
      - APP_ENV=prod
      - MONGODB_URI=mongodb://mongodb:27017
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=galaxy_empire_manager

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app

volumes:
  mongodb_data: 